### ISSUE TITLE
Change the ranking/level system

### ISSUE THREAD

**Issue by LucBerge** [anuraghazra/github-readme-stats#2265]
[![Custom badge](https://vote-badge.cyclic.app/view/github-readme-stats-issues-2265?label=Views&color=blue)](https://github.com/LucBerge/vote-badge)

I just discovered your repo and it is exactly what I need to create my user repo and user readme. Thank you for the amazing work you are doing here !

### Is your feature request related to a problem? Please describe.

I'm surprised by the ranking system currently used:
- B+ everyone
- A++ top 60%
- A+ top 45%
- S top 25%
- S+ top 1%

Most of the people who will see a github stats card like this won't understand the ranking system or will not understand it correctly. For me, A+ means really good user (or code quality) if you consider the ABCDEF ranking system.

To actually understand your ranking system, you need to click on the card, start reading the readme and find a little note explaining it.

The ranking label on the card must be obvious for anybody reading the card, whatever the job, nationality, education or culture.

### Describe the solution you'd like

Proposing my own ranking system won't be the ideal solution too. It will have a global impact on everybody, so I think **the community itself must debate to find the right ranking system** !

### Describe alternatives you've considered

Instead of a ranking system, you could just display the user rank in percentage:

![](https://www.pixenli.com/image/Scv3okXU)

### Additional context

**If you think this issue is relevant, consider pinning it so everybody can contribute.**

**Comment by rickstaa** [comment]
@LucBerge Thanks for your feature request. I agree with you that the ranking system is weird, and I think we are not the only ones since there have been multiple proposals and PRs open that try to improve the ranking:
- https://github.com/anuraghazra/github-readme-stats/issues/1560
- https://github.com/anuraghazra/github-readme-stats/issues/1579
- https://github.com/anuraghazra/github-readme-stats/issues/455
- https://github.com/anuraghazra/github-readme-stats/pull/960
- https://github.com/anuraghazra/github-readme-stats/pull/1186

I think two things can be improved about the ranking:
- Switch to a more commonly used grading system (i.e. A-F, A+ to F or % based).
- Show top-users percentage on hover (see https://stackoverflow.com/questions/41768657/display-text-over-svg-element-on-hover).
- Improve the rank calculation (see https://github.com/anuraghazra/github-readme-stats/pull/1186 and https://github.com/anuraghazra/github-readme-stats/pull/2116).

@anuraghazra I think we can merge https://github.com/anuraghazra/github-readme-stats/pull/2116 and https://github.com/anuraghazra/github-readme-stats/pull/1186 and switch to the A-F or A+ to F ranking system?

**Comment by rickstaa** [comment]
This is one of our most requested features, so I have looked at it (see https://github.com/anuraghazra/github-readme-stats/issues/1935). I, however, would like some feedback from @anuraghazra before merging https://github.com/anuraghazra/github-readme-stats/pull/2116 and https://github.com/anuraghazra/github-readme-stats/pull/1186.

**Comment by rickstaa** [comment]
#### TODOS

- [ ] Decide on a new grading system.
- [ ] Create PR that uses a more commonly used grading system (i.e. A-F, A+ to F or % based).
- [ ] Merge https://github.com/anuraghazra/github-readme-stats/pull/2116.
- [ ] Merge https://github.com/anuraghazra/github-readme-stats/pull/1186.
- [ ] Create PR that shows the top user percentage on hover (see https://github.com/anuraghazra/github-readme-stats/issues/2157).

**Comment by rickstaa** [comment]
@LucBerge I think the other ones would be the US ranking systems (see https://everydayeducation.com/blogs/news/grading-systems#:~:text=The%20most%20commonly%20used%20grading,100%20instead%20of%20letter%20grades).

- A-F.
- A+-F

I prefer these systems while showing the `%` based results on hover (see https://github.com/anuraghazra/github-readme-stats/issues/2157), but I might be biased let's see what @anuraghazra thinks.

**Comment by rickstaa** [comment]
We also have the Japanese ranking (see https://en.wikipedia.org/wiki/Academic_grading_in_Japan). Since only the `S+` is confusing for me, I think this one is also fine, but I think fewer people are familiar with that ranking system. So my vote still goes to the US-based ranking systems If we want to use letters.

**Comment by rickstaa** [comment]
> Well, I didn't know it was Japanese until now...

Same for me. I looked it up some months ago. It was the closest one I could find to the one GRS is using. 🤓 Maybe @anuraghazra can elaborate on which ranking system he based the GRS ranks on.

**Comment by ZjzMisaka** [comment]
![image](https://user-images.githubusercontent.com/16731853/202856894-dad0e5be-eb2a-4f53-af62-1412040b2709.png)
Maybe we can refer to the game rank, after all the developers spent a lot of time researching this

**Comment by rickstaa** [comment]
> Hello, I don't think the A-F system is a good idea. C, D and F are associated to a bad grade so it would be like "shaming" new devs because they have little contributions.

Good point we don't want that 😅!

**Comment by rickstaa** [comment]
> ![image](https://user-images.githubusercontent.com/16731853/202856894-dad0e5be-eb2a-4f53-af62-1412040b2709.png) Maybe we can refer to the game rank after all the developers spent a lot of time researching this

@ZjzMisaka Thanks for your input. That ranking system looks good to me very clear. It also is very close to the Japanese game ranking system @anuraghazra is currently using.

**Comment by rickstaa** [comment]
@ZjzMisaka, I think your suggestion is similar to the suggestion given in https://github.com/anuraghazra/github-readme-stats/issues/1560. I would go for your version since it doesn't include the F grade and is more commonly used. Let's see what @anuraghazra thinks.

**Comment by vezaynk** [comment]
Giving the lowest percentile a "B+" is bizarre. Based on the popularity of the project, I think it deserves a meaningful ranking system that doesn't use "A++" for half of users.

**Comment by Zo-Bro-23** [comment]
+1 for this, since A+, A++, S, S+, etc are confusing for me. @francois-rozet has a valid point about C, D, and E though, so maybe we should consider something different. Seeing the current ranks though, A++, A+, A, A-, B+, B, B- should be enough, which solves both the problems.

**Comment by vezaynk** [comment]
B- to say bottom percentile is weird as well.

Imagine if the top grade this gave was a C+ for top 1%. 

Same thing here.

**Comment by Zo-Bro-23** [comment]
> B- to say bottom percentile is weird as well.

Why do you say so? The problem with C and D is that they imply a "bad" user, which is not the case. So we have to make do with A and B alone.

**Comment by vezaynk** [comment]
C and D only mean "bad" because they're at the bottom. If you make B- at the bottom, it's not any better, just misleading.

**Comment by Zo-Bro-23** [comment]
> C and D only mean "bad" because they're at the bottom. If you make B- at the bottom, it's not any better, just misleading.

Well, the whole point of changing the ranking system is for users who have no idea what GRS is. When someone randomly comes across a GitHub profile, their impression is different for B and C, since they have no idea what ranking system we use.

The same is true for the current ranking system. I have an A+, which might impress people more than if I had an S, since they have no idea what S means.

**Comment by vezaynk** [comment]
In which case we could give everyone an S++++? You see what I'm saying?

**Comment by Zo-Bro-23** [comment]
> In which case we could give everyone an S++++? You see what I'm saying?

Yes. This is difficult 😕 @rickstaa thoughts?

**Comment by rickstaa** [comment]
> > In which case we could give everyone an S++++? You see what I'm saying?
> 
> Yes. This is difficult 😕 @rickstaa thoughts?

My vote is with the gaming rank system proposed by @ZjzMisaka (see https://github.com/anuraghazra/github-readme-stats/issues/2265#issuecomment-1320908160). I think that system togheter with a hover that explains the score solves our problems (see #2157). @anuraghazra what do you think?

**Comment by Zo-Bro-23** [comment]
> > > In which case we could give everyone an S++++? You see what I'm saying?
> > 
> > 
> > Yes. This is difficult confused @rickstaa thoughts?
> 
> My vote is with the gaming rank system proposed by @ZjzMisaka (see [#2265 (comment)](https://github.com/anuraghazra/github-readme-stats/issues/2265#issuecomment-1320908160)). I think that system togheter with a hover that explains the score solves our problems (see #2157). @anuraghazra what do you think?

Sure, that works. Can you add hover text to SVGs though?

**Comment by rickstaa** [comment]
> > > > In which case we could give everyone an S++++? You see what I'm saying?
> > > 
> > > 
> > > Yes. This is difficult confused @rickstaa thoughts?
> > 
> > 
> > My vote is with the gaming rank system proposed by @ZjzMisaka (see [#2265 (comment)](https://github.com/anuraghazra/github-readme-stats/issues/2265#issuecomment-1320908160)). I think that system togheter with a hover that explains the score solves our problems (see #2157). @anuraghazra what do you think?
> 
> Sure, that works. Can you add hover text to SVGs though?

It appears so (see https://stackoverflow.com/questions/41768657/display-text-over-svg-element-on-hover). I also was surprised; I didn't test it out yet. 😅

**Comment by Zo-Bro-23** [comment]
> > > > > In which case we could give everyone an S++++? You see what I'm saying?
> > > > 
> > > > 
> > > > Yes. This is difficult confused @rickstaa thoughts?
> > > 
> > > 
> > > My vote is with the gaming rank system proposed by @ZjzMisaka (see [#2265 (comment)](https://github.com/anuraghazra/github-readme-stats/issues/2265#issuecomment-1320908160)). I think that system togheter with a hover that explains the score solves our problems (see #2157). @anuraghazra what do you think?
> > 
> > 
> > Sure, that works. Can you add hover text to SVGs though?
> 
> It appears so (see https://stackoverflow.com/questions/41768657/display-text-over-svg-element-on-hover). I also was surprised; I didn't test it out yet. sweat_smile

That would be in HTML, yes? I doubt you can do that with GRS though, since the application returns an SVG image, and not an SVG image embedded in an HTML page. It's obviously great if you can do that, but even if it works in the browser, I doubt it will work in other places like GitHub READMEs.

**Comment by rickstaa** [comment]
So to summarize I think the following will improve the ranking of the stats card which is one of our most requested enhancements:

- Merging #1186 while setting the `STARS_WEIGHTS` to `0.75`.
- Creating a PR for @ZjzMisaka ranking suggestions (see https://github.com/anuraghazra/github-readme-stats/issues/2265#issuecomment-1320908160). Also document the new ranking in the [readme](https://github.com/anuraghazra/github-readme-stats/blob/master/readme.md).
- Create a PR for #2157.

However, since this affects all users I also want to have @anuraghazra's opinion.

**Comment by rickstaa** [comment]
> > > > > > In which case we could give everyone an S++++? You see what I'm saying?
> > > > > 
> > > > > 
> > > > > Yes. This is difficult confused @rickstaa thoughts?
> > > > 
> > > > 
> > > > My vote is with the gaming rank system proposed by @ZjzMisaka (see [#2265 (comment)](https://github.com/anuraghazra/github-readme-stats/issues/2265#issuecomment-1320908160)). I think that system togheter with a hover that explains the score solves our problems (see #2157). @anuraghazra what do you think?
> > > 
> > > 
> > > Sure, that works. Can you add hover text to SVGs though?
> > 
> > 
> > It appears so (see https://stackoverflow.com/questions/41768657/display-text-over-svg-element-on-hover). I also was surprised; I didn't test it out yet. sweat_smile
> 
> That would be in HTML, yes? I doubt you can do that with GRS though, since the application returns an SVG image, and not an SVG image embedded in an HTML page. It's obviously great if you can do that, but even if it works in the browser, I doubt it will work in other places like GitHub READMEs.

I support your conclusion. 🤔 I, however, did not test this out. Anyway, I would likely wait for #1633 to be implemented before trying to see if a hover works on the README. This proposal will improve our codebase a lot.

**Comment by chrisK824** [comment]
Hey there I joined some days ago in this cool project.
Is this feature going to be implemented after all?

**Comment by rickstaa** [comment]
> Hey there I joined some days ago in this cool project. Is this feature going to be implemented after all?

I am in favour of merging #1186 since it is more balanced (see https://github.com/anuraghazra/github-readme-stats/pull/1186#issuecomment-1382458487). I, however, would like to have @anuraghazra's opinion before making such a breaking change.

**Comment by ZjzMisaka** [comment]
Here is some suggestions of [Ranking System v2](https://github.com/anuraghazra/github-readme-stats/pull/1186#top), copied from https://github.com/anuraghazra/github-readme-stats/pull/1186#issuecomment-1556622639

> The new system is good, but I'd like to express my personal opinion. I believe that a grading system with only S, A, B tiers is not very good, because people might unconsciously believe that there exist tiers like C, D, F. I've previously stated that a "grading system that satisfies everyone" could ultimately lose its reference value, and the meaning represented by the rank "B" could eventually become the new F.
> 
> I trust that people's spirits are not so fragile that they cannot face their own grades, and even lower grades can serve as motivation for personal growth. We don't have to view this system as competitive ranking, instead, we can try to understand this system as a measure of a developer's "growth from the initial state". If we really don't want the grade F to appear, we could use a format like Lv1, Lv2, Lv3... and so forth.

or, if you're willing, you can also consider the content mentioned in the https://github.com/anuraghazra/github-readme-stats/issues/2265#issuecomment-1320902200

**Comment by rickstaa** [comment]
> #2265 (comment)

@ZjzMisaka thanks for including your comment here. My preference is still with https://github.com/anuraghazra/github-readme-stats/issues/2265#issuecomment-1320902200 👍🏻.

**Comment by SwastikGorai** [comment]
Seems they changed the ranking system after all. Many who were by default given A+ are now down to B. A++ is  now A

**Comment by rickstaa** [comment]
> Seems they changed the ranking system after all. Many who were by default given A+ are now down to B. A++ is now A

@SwastikGorai your right I decided to merge https://github.com/anuraghazra/github-readme-stats/pull/2749 since it was requested by many people. As explained in that issue, the old ranking function almost everybody A+ and made it nearly impossible to get a higher or lower ranking 😅. As a result, @francois-rozet proposed a new ranking version that is more well-balanced and motivates people to contribute to OS project and follow good code practices.

This issue (i.e. 2265) is about improving the ranking even further by changing the ranking levels. My preference currently is with https://github.com/anuraghazra/github-readme-stats/issues/2265#issuecomment-1320902200, but I would like to discuss this with the community and the other maintainers since it is a big change.

**Comment by lorezyra** [comment]
If the ranking system could be explained, then I can easily reference it when posting my stats on my websites.

**Comment by timheuer** [comment]
Just adding my feedback to this one as well.  I actually thought there was a bug that I was getting "S" in my card view.  Was about to log an issue and saw this thread.  Noticed "S" is actually quite good (yay!) but the single letter meant nothing to me (US educated, 'grading' system A-F).  I like the original image at the start of this post of the "Top X%" in the inner ring, that's cool and clear.  Anyhow, thanks for this project, but +1 comment here that "S" seems weird without explanation.

**Comment by vezaynk** [comment]
Prominent percentiles in some way are ideal imo

Letters are culture-dependent

**Comment by lorezyra** [comment]
Instead of some letter, why not use what most apps do in gamification: show an XP or numerical level rank? Everyone starts from zero. But few can keep pushing the top.

**Comment by rickstaa** [comment]
> If the ranking system could be explained, then I can easily reference it when posting my stats on my websites.

Does #2749 fit your need?

**Comment by rickstaa** [comment]
> oticed "S" is actually quite good (yay!) but the single letter meant nothing to me (US educated, 'grading' system A-F). I like the original image at the start of this post of the "Top X%" in the inner ring, that's cool and clear. Anyhow, thanks for this project, but +1 comment here that "S" seems weird without explan

With those stats, you deserve an S 🚀. The current ranking system is based on the Japanese system, I think. I however, still want to improve it to make it more general. My current preference is with https://github.com/anuraghazra/github-readme-stats/issues/2265#issuecomment-1320908160, but a level - based ranking system as given by @lorezyra would also work. Please have no hesitation to put your suggestions in here. I will likely open a poll when the new rank calculation has been merged for a while (i.e. https://github.com/anuraghazra/github-readme-stats/pull/1186).

**Comment by francois-rozet** [comment]
To add my grain of salt, is "S" really that hard to understand? It is extremely common in games and means "super"/"more-than-perfect". If you type "tier list" on google images, you will find it everywhere. However what I don't like with the current system is the "S+", which makes no sense. So what I would do as a first step is remove "S+" and add "C" and "C+" (but not below as "E" and "F" are associated with failure). I would also separate the levels evenly (currently the step between "A" and "A+" is much smaller than "B" and "B+") to make it more motivational for newcomers.

I also like the "top x%" (or simply x% and the goal would be to reach 100%); it is the less confusing. I like the idea of "unbounded XP", but this will lead to display issues when the number gets large.

**Comment by lorezyra** [comment]
@francois-rozet 
> To add my grain of salt, is "S" really that hard to understand? It is extremely common in games and means "super"/"more-than-perfect". If you type "tier list" on google images, you will find it everywhere. However what I don't like with the current system is the "S+", which makes no sense. So what I would do as a first step is remove "S+" and add "C" and "C+" (but not below as "E" and "F" are associated with failure). I would also separate the levels evenly (currently the step between "A" and "A+" is much smaller than "B" and "B+") to make it more motivational for newcomers.

First, not everyone plays games. I'm over 40 and don't have time to play games anymore. (Too busy writing code and chasing money...) 

Second, despite living in Japan for the past 15 years, I have never encountered [Academic grading in Japan](https://en.wikipedia.org/wiki/Academic_grading_in_Japan) system. Perhaps it's relatively new and not implemented widely? My point is that not everyone is aware nor familiar with it. Without documentation to explain it, it's a meaningless indicator.


> I also like the "top x%" (or simply x% and the goal would be to reach 100%); it is the less confusing. I like the idea of "unbounded XP", but this will lead to display issues when the number gets large.

I'm not sure "100%" would be all that meaningful either. "100%" of what? I like the unbounded XP / level ranking idea. If the numbers get too big, it's trivial to use metric notation to denote larger numbers - _e.g._ 1K, 99M, 12B... or, use: 3x10^6? The numbers combined with letters would be easier to display. (12M)

That said, "top %" may be more meaningful to recruiters and social circles that value that data.

**Comment by guylepage3** [comment]
> Prominent percentiles in some way are ideal imo
> 
> Letters are culture-dependent
> 

I agree with @vezaynk. Letters don't work for everyone where as percentiles do.

**Comment by rickstaa** [comment]
I agree with. I don't think the current ranking system is bad, but it can be improved. I think the suggestions you made will greatly improve the ranking:

- Remove the S+ ranking, since it is not in the [Japanese Grading system](https://en.wikipedia.org/wiki/Academic_grading_in_Japan) anyway.
- Add extra ranks between S-C (i.e. S, A+, A, B+, B, C+, C) while omitting the D and F rankings since they are associated with bad grades.
- Device ranks evenly.

You are welcome to create a pull request if you like. I am willing to merge these changes without the approval of @anuraghazra. If we want to switch to other ranking systems, I would first like to discuss this with @anuraghazra.

@lorezyra and @guylepage3 About the percentage-based ranking system, I think this is redundant since the rank circle already shows the percentage:

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=rickstaa)](https://github.com/anuraghazra/github-readme-stats)

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=francois-rozet)](https://github.com/anuraghazra/github-readme-stats)

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=lorezyra)](https://github.com/anuraghazra/github-readme-stats)

The level/XP-based system indeed is a candidate, but I think will require a lot of code and therefore could hamper the maintainability of the repository. Since GRS is a fun OS project and not a certified skill evolution tool for recruitment, this might not be worth it 🤔.

**Comment by lorezyra** [comment]
@rickstaa,

Okay. Recommend better docs to explain the meaning of the circle and letters inside the circle. I think it's fantastic to have this tool. Perhaps if you had more sponsorships, an XP based system to be devised to support users that want to show off to recruiters. Until then, whatever the method to determine the rank, please provide documentation that I can link to on my sites.

**Comment by guylepage3** [comment]
> @rickstaa,
> 
> 
> 
> Okay. Recommend better docs to explain the meaning of the circle and letters inside the circle. I think it's fantastic to have this tool. Perhaps if you had more sponsorships, an XP based system could be devised to support users that want to show off to recruiters. Until then, whatever the method to determine the rank, please provide documentation that I can link to on my sites.

💯 agree that this is now needed. I did some basic anecdotal evidence that people in North America only understand up to A++. Anything beyond that doesn't exist. A full explanation would be required for N.A. audiences.

**Comment by rickstaa** [comment]
> @rickstaa,
> 
> Okay. Recommend better docs to explain the meaning of the circle and letters inside the circle. I think it's fantastic to have this tool. Perhaps if you had more sponsorships, an XP based system could be devised to support users that want to show off to recruiters. Until then, whatever the method to determine the rank, please provide documentation that I can link to on my sites.

@guylepage3 and @lorezyra I updated https://github.com/anuraghazra/github-readme-stats/pull/2749/files so that it explains both the ranking system it is based on and the meaning of the circle around the rank. We can update this when the suggestions made by @francois-rozet are implemented 👍🏻.

**Comment by rickstaa** [comment]
@guylepage3 I just checked your README page and it looks wonderful. I love https://guylepage3.vercel.app/. Just wondering. What is the reason that you decided to use https://github.com/brunobritodev/awesome-github-stats's version instead of the upstream 🤔? Are there any features GRS is missing?

**Comment by rickstaa** [comment]
> @rickstaa,
> 
> Okay. Recommend better docs to explain the meaning of the circle and letters inside the circle. I think it's fantastic to have this tool. Perhaps if you had more sponsorships, an XP based system could be devised to support users that want to show off to recruiters. Until then, whatever the method to determine the rank, please provide documentation that I can link to on my sites.

I think switching to an organization would already improve maintainability, since it will give me more control about who can collaborate (see https://github.com/anuraghazra/github-readme-stats/issues/1867). I noticed that many people are passionate about this project and want to contribute, but the permission control of a personal repository limits this 😅.

**Comment by rickstaa** [comment]
For future reference, I also merged a pull request some months ago which allows you to replace the rank with a GitHub logo using the `rank_icon` flag. When this is done, it only shows the percentage.

```md

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&rank_icon=github)](https://github.com/anuraghazra/github-readme-stats)
```

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&rank_icon=github)](https://github.com/anuraghazra/github-readme-stats)

**Comment by rickstaa** [comment]
> @guylepage3 I just checked your README page and it looks wonderful. I love https://guylepage3.vercel.app/. Just wondering. What is the reason that you decided to use https://github.com/brunobritodev/awesome-github-stats version instead of the upstream thinking? Are there any features GRS is missing?

One feature I see of that fork that would be nice in the upstream is the card generation website (see https://github.com/anuraghazra/github-readme-stats/issues/1761) 🤔.

**Comment by chrisK824** [comment]
@rickstaa I'll agree with guys that support percentage number is the most efficient here.

Pros
-  global regardless the culture/ranking systems around countries
- extra resolution down to 1% changes that can motivate the user, so just doing what the ranking is supposed to do in the first place
- easily compare all users rather than group them in big clusters (just in case this is used for any kind of comparison/evaluation)

**Comment by guylepage3** [comment]
> @guylepage3 I just checked your README page and it looks wonderful. I love https://guylepage3.vercel.app/. Just wondering. What is the reason that you decided to use https://github.com/brunobritodev/awesome-github-stats 's version instead of the GRS 🤔? Are there any features GRS is missing?

@rickstaa Thanks for the kind words 😄. And yes. I reached out to @brunobritodev a little while back. He seems to have, although not perfect, a bit better structure for ranking. At the time of me creating https://guylepage3.vercel.app/. I will have to check out the upcoming results of future releases here in the not so distant future. Also I have a lot to complete with https://guylepage3.vercel.app/.

>Are there any features GRS is missing?

I believe the value of commits to stars is calculated and valued differently. Stars, imo, are usually just well-marketed projects. Marketing, although important, is not a determining factor in what makes a great developer. Again, imo.

**Comment by anarchopossum** [comment]
I personally Like the numerical ranking system. Not only is it more universal for people around the world to understand. it keeps people motivated to keep working. Seeing a letter value might demote someone from wanting to work or it might not translate very well for other regions outside of the US

**Comment by rickstaa** [comment]
> I personally Like the numerical ranking system. Not only is it more universal for people around the world to understand. it keeps people motivated to keep working. Seeing a letter value might demote someone from wanting to work or it might not translate very well for other regions outside of the US

Maybe we can give the user the ability to set the `rank_type` to `number` or `letter`? We could use the inverse of the number that is used to calculate the rank 🤔.

**Comment by rickstaa** [comment]
> > I personally Like the numerical ranking system. Not only is it more universal for people around the world to understand. it keeps people motivated to keep working. Seeing a letter value might demote someone from wanting to work or it might not translate very well for other regions outside of the US
> 
> Maybe we can give the user the ability to set the `rank_type` to `number` or `letter`? We could use the inverse of the number that is used to calculate the rank thinking.

Closing this because #2762 in my opinion, improved the ranking level system by a great around! Feel welcome to open a new issue or pull request if you guys want to have the ability to show the percentage complete instead of the ranking letters 👍🏻.

**Comment by rickstaa** [comment]
I just created https://github.com/anuraghazra/github-readme-stats/pull/2858, which, when merged, gives users the ability to show the rank progress instead.

```md
![Anurag's GitHub stats](https://github-readme-stats-git-addprogressrankicon-rickstaa.vercel.app/api?username=anuraghazra\&rank_icon=progress)
```

![Anurag's GitHub stats](https://github-readme-stats-git-addprogressrankicon-rickstaa.vercel.app/api?username=anuraghazra\&rank_icon=progress)

**Comment by rickstaa** [comment]
Additionally, I now created #2859, which gives users the ability to show the `percentile`:

```md
[![Anurag's GitHub stats](https://github-readme-stats-git-addpercentilerankicon-rickstaa.vercel.app/api?username=mindlabordev&rank_icon=percentile)](https://github.com/anuraghazra/github-readme-stats)
```

[![Anurag's GitHub stats](https://github-readme-stats-git-addpercentilerankicon-rickstaa.vercel.app/api?username=mindlabordev&rank_icon=percentile&random=12345)](https://github.com/anuraghazra/github-readme-stats)

**Comment by rickstaa** [comment]
We decided to replace progress with percentile since it is unclear to users what progress means (see https://github.com/anuraghazra/github-readme-stats/pull/2859#pullrequestreview-1487346398). Therefore, changing progress to percentile in your README would be best.
